# Generated by Django 2.2.10 on 2021-01-27 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_username', models.CharField(max_length=32)),
                ('answer_likes', models.IntegerField(default=0)),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_username', models.CharField(max_length=32)),
                ('question_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_likes', models.IntegerField(default=0)),
                ('question_text', models.TextField()),
            ],
        ),
    ]
