# Generated by Django 2.2.10 on 2021-01-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
