# Generated by Django 2.2.10 on 2021-01-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='main.Question'),
        ),
    ]
