# Generated by Django 2.2.10 on 2021-01-27 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_answer_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_username',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
