# Generated by Django 2.2.10 on 2021-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210127_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
