# Generated by Django 2.2.10 on 2021-01-28 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210127_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_dislikes',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_dislikes',
            field=models.ManyToManyField(related_name='user_answer_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_likes',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_likes',
            field=models.ManyToManyField(related_name='user_answer_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_dislikes',
        ),
        migrations.AddField(
            model_name='question',
            name='question_dislikes',
            field=models.ManyToManyField(related_name='user_question_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_likes',
        ),
        migrations.AddField(
            model_name='question',
            name='question_likes',
            field=models.ManyToManyField(related_name='user_question_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
